sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: XADNc+uW7Dok+/bm1aRWvJkguxKEHD4vdzT9tHAsnppWBFTI2+3W0eUlTs2r4sCmPs1VYM08fgyypnfOXohTooA8iLYZiuFAXG60qLp9mQE411GCrsY7fJITd2f2piSJQSuarFq3rbzykiuBxEsOPXrYGzYnowvylsCm/KV3wjzJvXPYDPwFPDQHYFl+Ty+4vFe3F1QcXTKHv0rbAybzpfs59TpL7ytp684xQOEgwxVz/ybQ8pOc14Db4r1tTcu5dDxoD+Se6J2OLy3Q+mwfm9SrRCfeWbZBPFPsXcowBFg+765f5/bBEm8x6nJpSAKYWvrumHdvMAs1RzOZUzfczuoJqmf1cDB3G5LQZutHhLHZaraivDO56NsdSUun+2Oo51Sn7sLjVX3LtWkuZjwcdvErmek+9aszxbRnUVNL8+1Qyx35JwwG5dj2M7ssHvMhv54ZDDMMaoWUV9SQpcTiGYI2KcWDvGrEo5QJdo/jlFaVas7BMRfnoFTA4dDyyww0/jbd05afqhun3Z8I7A//fCxTuQzBgUXNcE7XsvlCSEhnGFGPCVyTHKYh95MaHWmV9CrM7VPB4JtNd39IpT7q/z+BYhXy8sXdasEr8uKbIMbxG4MHol7pwadq3Q1ULwLv5Hs5VyCCG4sZkQrjlhOAr4OZSR1wpoXDirRxFd4z7po=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Tragedy-of-King-Richard-III_1503
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy